### ISSUE TITLE
Run-app command should save the current editor before building

### ISSUE THREAD

**Issue by mit-mit** [dartino/atom-dartino#10]
The run-app-in-device command compiles the file in the current editor tab into a flashable image. If the user forgets to save first, it will compile whatever file is on disk. To be consistent with IDE expectations, we should auto-save the current editor before we compile, i.e., run something like these commands:

```
  editor = atom.workspace.getActiveTextEditor()
  editor.save()
```

**Comment by danrubel** [comment]
Fixed. https://github.com/dartino/atom-dartino/commit/06aa1d1a5a1312140ffb823020090fd87c11d020
