### ISSUE TITLE
consolidate and auto-close build/deploy/launch dialog(s)

### ISSUE THREAD

**Issue by danrubel** [dartino/atom-dartino#6]
When you launch a Dartino or SoD app, you see several dialogs and they "build up" over time as you repeatedly write code - launch - repeat. Dialogs from prior launches should auto-close during a new launch and the separate build, deploy, and launch dialogs should be consolidated.

**Comment by mit-mit** [comment]
I actually think the dialog should just dismiss itself based on a timer (say, after 1 minute) if possible
